# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa5ea219458e9df36503fe4d930538b3bd39c4e52d7f78aa6345c02fb79c79a7ce3b2c076433ceaf9d02788ef439790e32101c678813ec80b615483fe894e747

test:
  secret_key_base: 954fb52b317a550d02dec3384ffc494c242faeb0febdf971dbb618b03188966234f99b4329b02b62e0f739bf91eba681fcef0ce37a050d1d97ea74d40a24311c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
